<Project>
  <Target Name="ShowBuildInfo" BeforeTargets="CoreCompile" Condition="'$(MSBuildProjectName)' == 'DXMainClient'">
    <Message Importance="high" Text="Engine: $(Engine); Platform: $(Platform); TargetFramework: $(TargetFramework); Configuration: $(Configuration)" />
  </Target>

  <!-- "GetVersion" target is defined in GitVersion package -->
  <Target Name="NonReleaseBuildWarning" AfterTargets="GetVersion" BeforeTargets="CoreCompile" Condition="'$(MSBuildProjectName)' == 'DXMainClient' AND ($(GitVersion_CommitsSinceVersionSource) != 0)">
    <PropertyGroup>
      <DefineConstants>$(DefineConstants);DEVELOPMENT_BUILD</DefineConstants>
    </PropertyGroup>
    <Warning Text="This is a development build of the client. Stability and reliability may not be fully guaranteed." Condition="'$(BuildingInsideVisualStudio)' != 'true'"></Warning>
  </Target>

  <Target Name="RestoreUpdater" AfterTargets="Restore" Condition="'$(PublishDir)' != '' AND '$(MSBuildProjectName)' == 'AvClientExe'">
    <MSBuild
      Projects="$(MSBuildThisFileDirectory)SecondStageUpdater\SecondStageUpdater.csproj"
      Properties="TargetFramework=$(TargetFramework.Split('-')[0]);Platform=AnyCPU;RuntimeIdentifier="
      Targets="Restore" />
  </Target>

  <Target Name="BuildUpdater" AfterTargets="Build" Condition="'$(PublishDir)' != '' AND '$(MSBuildProjectName)' == 'AvClientExe'">
    <MSBuild
      Projects="$(MSBuildThisFileDirectory)SecondStageUpdater\SecondStageUpdater.csproj"
      Properties="TargetFramework=$(TargetFramework.Split('-')[0]);Platform=AnyCPU;RuntimeIdentifier=" />
  </Target>

  <Target Name="CopyResources" AfterTargets="Build" Condition="$(DefineConstants.Contains('DEBUG')) AND '$(MSBuildProjectName)' == 'AvClientExe'">
    <ItemGroup>
      <ExampleClientResources Include="$(MSBuildProjectDirectory)\Resources\DTA\**\*.*" />
      <ExampleClientMaps Include="$(MSBuildProjectDirectory)\Resources\Maps\**\*.*" />
      <ExampleClientIni Include="$(MSBuildProjectDirectory)\Resources\INI\**\*.*" />
      <ExampleClientMix Include="$(MSBuildProjectDirectory)\Resources\MIX\**\*.*" />
      <ExampleClientSettings Include="$(MSBuildProjectDirectory)\Resources\SUN.ini" />
      <ExampleClientDefinitions Include="$(MSBuildProjectDirectory)\Resources\ClientDefinitions.ini" />
    </ItemGroup>
    <Copy Condition="! Exists('$(OutputPath)\Resources\ClientDefinitions.ini') " SourceFiles="@(ExampleClientResources)" DestinationFolder="$(OutputPath)\Resources\%(RecursiveDir)" />
    <Copy Condition="! Exists('$(OutputPath)\Resources\ClientDefinitions.ini') " SourceFiles="@(ExampleClientMaps)" DestinationFolder="$(OutputPath)\Maps\%(RecursiveDir)" />
    <Copy Condition="! Exists('$(OutputPath)\Resources\ClientDefinitions.ini') " SourceFiles="@(ExampleClientIni)" DestinationFolder="$(OutputPath)\INI\%(RecursiveDir)" />
    <Copy Condition="! Exists('$(OutputPath)\Resources\ClientDefinitions.ini') " SourceFiles="@(ExampleClientMix)" DestinationFolder="$(OutputPath)\MIX\%(RecursiveDir)" />
    <Copy Condition="! Exists('$(OutputPath)\Resources\ClientDefinitions.ini') " SourceFiles="@(ExampleClientSettings)" DestinationFolder="$(OutputPath)" />
    <Copy Condition="! Exists('$(OutputPath)\Resources\ClientDefinitions.ini') " SourceFiles="@(ExampleClientDefinitions)" DestinationFolder="$(OutputPath)\Resources" />
  </Target>

  <Target Name="CopyUpdater" AfterTargets="Build" Condition="'$(PublishDir)' != '' AND '$(MSBuildProjectName)' == 'SecondStageUpdater'">
    <PropertyGroup>
      <CNCNetUpdaterCopyTo>$(PublishDir)\..\Updater\</CNCNetUpdaterCopyTo>
    </PropertyGroup>
    <ItemGroup>
      <CNCNetUpdaterOutputFile Include="$(OutputPath)\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(CNCNetUpdaterOutputFile)" DestinationFolder="$(CNCNetUpdaterCopyTo)" />
  </Target>

  <Target Name="MoveUpdater" Condition="'$(MSBuildProjectName)' == 'SecondStageUpdater'">
    <Message Importance="high" Text="Moving updater executables" />
    <Move SourceFiles="%(CNCNetUpdaterOutputFile.Identity)" DestinationFolder="$(CNCNetUpdaterCopyTo)" Condition="!Exists('$(CNCNetUpdaterCopyTo)%(CNCNetUpdaterOutputFile.Identity)')" />
    <Delete Files="%(CNCNetUpdaterOutputFile.Identity)" Condition="Exists('$(CNCNetUpdaterCopyTo)%(CNCNetUpdaterOutputFile.Identity)')" />
  </Target>

  <!-- Allow a game specific build prop file to be imported, if available -->
  <Import Project="$(MSBuildThisFileDirectory)Directory.targets" Condition="Exists('$(MSBuildThisFileDirectory)Directory.targets')" />

</Project>
