<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>CnCNet Client Core Library</Description>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" />
    <PackageReference Include="Ude.NetStandard" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Sinks.Trace" />
    <PackageReference Include="SerilogTraceListener" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rampastring.XNAUI\Rampastring.Tools\Rampastring.Tools.csproj" />
  </ItemGroup>
</Project>
