<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>DXMainClientViewModel</RootNamespace>
    <AssemblyName>DXMainClientViewModel</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="DiscordRichPresence" />
    <PackageReference Include="lzo.net" />
    <PackageReference Include="OpenMcdf" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.DirectoryServices" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClientCore\ClientCore.csproj" />
    <ProjectReference Include="..\ClientUpdater\ClientUpdater.csproj" />
    <ProjectReference Include="..\DXMainClientMvvmContract\DXMainClientMvvmContract.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
