<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <RootNamespace>AvClientViewModel</RootNamespace>
    <AssemblyName>AvClientViewModel</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="DiscordRichPresence" />
    <PackageReference Include="lzo.net" />
    <PackageReference Include="OpenMcdf" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="Facepunch.Steamworks" GeneratePathProperty="true" />
    <PackageReference Include="System.DirectoryServices" />
    <PackageReference Include="Serilog" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClientCore\ClientCore.csproj" />
    <ProjectReference Include="..\ClientUpdater\ClientUpdater.csproj" />
    <ProjectReference Include="..\AvClientMvvmContract\AvClientMvvmContract.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <None Include="$(PkgFacepunch_Steamworks)\content\steam_api64.dll">
      <Link>x64/steam_api64.dll</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' != '.NETFramework'">
    <None Include="$(PkgFacepunch_Steamworks)\content\steam_api64.dll">
      <Link>runtimes/win-x64/native/steam_api64.dll</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
