<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    <Platforms>AnyCPU</Platforms>
    <Nullable>enable</Nullable>
    <RootNamespace>AvMainClientView</RootNamespace>
    <AssemblyName>AvMainClientView</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Themes.Simple" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AvMainClientMvvmContract\AvMainClientMvvmContract.csproj" />
    <ProjectReference Include="..\ClientCore\ClientCore.csproj" />
  </ItemGroup>
</Project>
