[MultiMaps]
0=Maps/Tiberian Sun/terrace
1=Maps/Firestorm/duel
2=Maps/Fan-made/pain_redefined
3=Maps/Fan-made/cold_war

[GameModeAliases]
Standard=Custom Map
standard=Custom Map

[Maps/Tiberian Sun/terrace]
CD=0,1,2
;MinPlayers=1
MaxPlayers=4
Description=[4] Terrace
Author=Westwood Studios
EnforceMaxPlayers=False
Size=0,0,120,120
LocalSize=2,4,116,109
PreviewSize=800,386
GameModes=Default
Waypoint0=118035
Waypoint1=110188
Waypoint2=199114
Waypoint3=29130

[Maps/Firestorm/duel]
CD=0,1,2
;MinPlayers=1
MaxPlayers=2
Description=[2] FS Dueling Islands
Author=Westwood Studios
EnforceMaxPlayers=False
Size=0,0,88,69
LocalSize=0,0,88,69
PreviewSize=800,302
GameModes=Default
Waypoint0=107064
Waypoint1=58083

[Maps/Fan-made/pain_redefined]
CD=0,1,2
;MinPlayers=1
MaxPlayers=2
Description=[2] Pain Redefined
Author=Aro
EnforceMaxPlayers=False
Size=0,0,65,80
LocalSize=2,4,61,69
PreviewSize=800,482
GameModes=Fan-made
Waypoint0=111087
Waypoint1=68031

[Maps/Fan-made/cold_war]
CD=0,1,2
;MinPlayers=1
MaxPlayers=3
Description=[3] Cold War
Author=Aro
EnforceMaxPlayers=False
Size=0,0,75,88
LocalSize=2,4,71,78
PreviewSize=800,465
GameModes=Fan-made
Waypoint0=51047
Waypoint1=136094
Waypoint2=88128
