<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>DXMainClientMVVMContract</RootNamespace>
    <AssemblyName>DXMainClientMVVMContract</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClientCore\ClientCore.csproj" />
  </ItemGroup>
</Project>
