
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using ClientCore;
using ClientCore.Extensions;
using DXMainClientViewModel.Campaign;
using DXMainClientViewModel.Domain;
using Rampastring.Tools;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace DXMainClientViewModel.Generic
{
    /// <summary>
    /// ViewModel for loading saved singleplayer games.
    /// </summary>
    public partial class GameLoadingWindowViewModel : ObservableObject, IGameLoadingWindowViewModel
    {
        private const string SAVED_GAMES_DIRECTORY = "Saved Games";

        private readonly IGameProcessService gameProcessService;
        private readonly IDiscordHandlerService discordHandler;
        private readonly ICampaignSelectorViewModel campaignSelectorViewModel;

        [ObservableProperty]
        private List<SavedGame> savedGames = new();

        [ObservableProperty]
        private int selectedSavedGameIndex = -1;

        [ObservableProperty]
        private bool canLoadGame;

        [ObservableProperty]
        private bool canDeleteSavedGame;

        [ObservableProperty]
        private List<string> savedGameNames = new();

        [ObservableProperty]
        private bool isVisible;

        [ObservableProperty]
        private bool showDeleteConfirmation;

        [ObservableProperty]
        private string deleteConfirmationMessage = string.Empty;

        public GameLoadingWindowViewModel(
            IGameProcessService gameProcessService,
            IDiscordHandlerService discordHandler,
            ICampaignSelectorViewModel campaignSelectorViewModel)
        {
            this.gameProcessService = gameProcessService;
            this.discordHandler = discordHandler;
            this.campaignSelectorViewModel = campaignSelectorViewModel;
        }

        partial void OnSelectedSavedGameIndexChanged(int value)
        {
            bool hasSelection = value >= 0 && value < SavedGames.Count;
            CanLoadGame = hasSelection;
            CanDeleteSavedGame = hasSelection;
        }

        partial void OnIsVisibleChanged(bool value)
        {
            if (value)
                ListSaves();
        }

        /// <summary>
        /// Opens the window and refreshes the saved games list.
        /// </summary>
        public void Open()
        {
            ListSaves();
            IsVisible = true;
        }

        [RelayCommand]
        private void LoadGame()
        {
            if (SelectedSavedGameIndex < 0 || SelectedSavedGameIndex >= SavedGames.Count)
                return;

            SavedGame sg = SavedGames[SelectedSavedGameIndex];
            Logger.Log("Loading saved game " + sg.FileName);

            Mission mission = campaignSelectorViewModel.UniqueIDToMissions
                .GetValueOrDefault(sg.CustomMissionID, null);

            CustomMissionHelper.DeleteSupplementalMissionFiles();

            if (mission != null)
                CustomMissionHelper.CopySupplementalMissionFiles(mission);

            FileInfo spawnerSettingsFile = SafePath.GetFile(ProgramConstants.GamePath, ProgramConstants.SPAWNER_SETTINGS);

            if (spawnerSettingsFile.Exists)
                spawnerSettingsFile.Delete();

            IniFile spawnIni = new()
            {
                Comment = "Generated by CnCNet Client"
            };

            IniSection spawnIniSettings = new("Settings");
            spawnIniSettings.AddKey("Scenario", "spawnmap.ini");
            spawnIniSettings.AddKey("SaveGameName", sg.FileName);
            spawnIniSettings.AddKey("LoadSaveGame", "Yes");
            spawnIniSettings.AddKey("SidebarHack", ClientConfiguration.Instance.SidebarHack.ToString());
            spawnIniSettings.AddKey("CustomLoadScreen", LoadingScreenController.GetLoadScreenName("g"));
            spawnIniSettings.AddKey("Firestorm", "No");
            spawnIniSettings.AddKey("GameSpeed", UserINISettings.Instance.GameSpeed.ToString());

            spawnIni.AddSection(spawnIniSettings);

            if (mission != null)
            {
                spawnIniSettings.AddKey("CustomMissionID", sg.CustomMissionID.ToString());
                WriteMissionSectionToSpawnIni(spawnIni, mission);
            }

            spawnIni.WriteIniFile(spawnerSettingsFile.FullName);

            FileInfo spawnMapIniFile = SafePath.GetFile(ProgramConstants.GamePath, "spawnmap.ini");

            if (spawnMapIniFile.Exists)
                spawnMapIniFile.Delete();

            using (var spawnMapStreamWriter = new StreamWriter(spawnMapIniFile.FullName))
            {
                spawnMapStreamWriter.WriteLine("[Map]");
                spawnMapStreamWriter.WriteLine("Size=0,0,50,50");
                spawnMapStreamWriter.WriteLine("LocalSize=0,0,50,50");
                spawnMapStreamWriter.WriteLine();
            }

            discordHandler.SetSavedGamePresence(sg.GUIName, true);

            IsVisible = false;
            gameProcessService.GameProcessExited += OnGameProcessExited;
            gameProcessService.StartGameProcess();
        }

        [RelayCommand]
        private void DeleteSavedGame()
        {
            if (SelectedSavedGameIndex < 0 || SelectedSavedGameIndex >= SavedGames.Count)
                return;

            SavedGame sg = SavedGames[SelectedSavedGameIndex];
            DeleteConfirmationMessage = string.Format(
                "The following saved game will be deleted permanently:\n\n" +
                "Filename: {0}\n" +
                "Saved game name: {1}\n" +
                "Date and time: {2}\n\n" +
                "Are you sure you want to proceed?",
                sg.FileName, sg.GUIName, sg.LastModified.ToString());

            ShowDeleteConfirmation = true;
        }

        [RelayCommand]
        private void ConfirmDelete()
        {
            ShowDeleteConfirmation = false;

            if (SelectedSavedGameIndex < 0 || SelectedSavedGameIndex >= SavedGames.Count)
                return;

            SavedGame sg = SavedGames[SelectedSavedGameIndex];

            Logger.Log("Deleting saved game " + sg.FileName);
            SafePath.DeleteFileIfExists(ProgramConstants.GamePath, SAVED_GAMES_DIRECTORY, sg.FileName);
            ListSaves();
        }

        [RelayCommand]
        private void CancelDelete()
        {
            ShowDeleteConfirmation = false;
        }

        [RelayCommand]
        private void Cancel()
        {
            IsVisible = false;
        }

        [RelayCommand]
        private void Refresh()
        {
            ListSaves();
        }

        private void OnGameProcessExited()
        {
            gameProcessService.GameProcessExited -= OnGameProcessExited;

            CustomMissionHelper.DeleteSupplementalMissionFiles();

            discordHandler.ClearPresence();

            IsVisible = false;
        }

        /// <summary>
        /// Loads and parses all saved games from the Saved Games directory.
        /// </summary>
        public void ListSaves()
        {
            SavedGames.Clear();
            SavedGameNames.Clear();
            SelectedSavedGameIndex = -1;

            DirectoryInfo savedGamesDirectoryInfo = SafePath.GetDirectory(ProgramConstants.GamePath, SAVED_GAMES_DIRECTORY);

            if (!savedGamesDirectoryInfo.Exists)
            {
                Logger.Log("Saved Games directory not found!");
                return;
            }

            IEnumerable<FileInfo> files = savedGamesDirectoryInfo.EnumerateFiles("*.SAV", SearchOption.TopDirectoryOnly);

            foreach (FileInfo file in files)
            {
                ParseSaveGame(file.FullName);
            }

            SavedGames = SavedGames.OrderByDescending(sg => sg.LastModified.Ticks).ToList();
            SavedGameNames = SavedGames.Select(sg => sg.GUIName ?? sg.FileName).ToList();
        }

        private void ParseSaveGame(string fileName)
        {
            string shortName = Path.GetFileName(fileName);

            SavedGame sg = new SavedGame(shortName);
            if (sg.ParseInfo())
                SavedGames.Add(sg);
        }

        /// <summary>
        /// Writes mission section data to spawn INI file.
        /// </summary>
        public static void WriteMissionSectionToSpawnIni(IniFile spawnIni, Mission mission)
        {
            bool hasGameMissionData = false;

            bool scenarioPathFound = mission.TryGetScenarioFilePath(out string scenarioPath);
            if (!scenarioPathFound)
            {
                Logger.Log($"CampaignSelector: mission scenario contains invalid path characters. Mission code name: {mission.CodeName}. Scenario: {mission.Scenario}. This mission will be launched without mission section data.");
                return;
            }

            if (!mission.IsCustomMission && File.Exists(scenarioPath))
            {
                var mapIni = new IniFile(scenarioPath);
                mission.GameMissionConfigSection = mapIni.GetSection("GameMissionConfig");

                if (mission.GameMissionConfigSection is not null)
                    hasGameMissionData = true;
            }

            if (mission.IsCustomMission && mission.GameMissionConfigSection is not null || hasGameMissionData)
            {
                // copy an IniSection
                IniSection spawnIniMissionIniSection = new(mission.Scenario);
                string loadingScreenName = string.Empty;
                string loadingScreenPalName = string.Empty;
                foreach (var kvp in mission.GameMissionConfigSection.Keys)
                {
                    if (string.IsNullOrEmpty(kvp.Value))
                    {
                        if (kvp.Key.Equals("LS640BkgdName", StringComparison.InvariantCulture) || kvp.Key.Equals("LS800BkgdName", StringComparison.InvariantCulture))
                            loadingScreenName = kvp.Value;
                        else if (kvp.Key.Equals("LS800BkgdPal", StringComparison.InvariantCulture))
                            loadingScreenPalName = kvp.Value;
                    }

                    spawnIniMissionIniSection.AddKey(kvp.Key, kvp.Value);
                }

                if (string.IsNullOrEmpty(loadingScreenName))
                {
                    string lsFilename = CustomMissionHelper.CustomMissionSupplementDefinition.FirstOrDefault(x => x.extension.Equals("shp", StringComparison.InvariantCultureIgnoreCase)).filename;

                    if (!string.IsNullOrEmpty(lsFilename))
                    {
                        spawnIniMissionIniSection.AddOrReplaceKey("LS640BkgdName", lsFilename);
                        spawnIniMissionIniSection.AddOrReplaceKey("LS800BkgdName", lsFilename);
                    }
                }
                if (string.IsNullOrEmpty(loadingScreenPalName))
                {
                    string palFilename = CustomMissionHelper.CustomMissionSupplementDefinition.FirstOrDefault(x => x.extension.Equals("pal", StringComparison.InvariantCultureIgnoreCase)).filename;

                    if (!string.IsNullOrEmpty(palFilename))
                        spawnIniMissionIniSection.AddOrReplaceKey("LS800BkgdPal", palFilename);
                }

                // append the new IniSection
                spawnIni.AddSection(spawnIniMissionIniSection);
                spawnIni.SetStringValue("Settings", "ReadMissionSection", "Yes");
            }
        }
    }
}


